<?php
/**
 * Generated by yentu on 14th May, 2016 22:23:44
 */

begin()
    ->table('servers')
        ->column('server_id')->type('integer')->nulls(false)
        ->column('server_host_ip')->type('string')->nulls(false)
        ->column('server_name')->type('string')->nulls(false)
        ->primaryKey('server_id')->name('server_id_pk')->autoIncrement()
        ->unique('server_host_ip')->name('server_host_ip_uk')
->end();
