<?php
/**
 * Generated by yentu on 31st May, 2016 11:04:58
 */

begin()

    ->table('server_memories')
        ->column('server_memory_id')->type('integer')->nulls(false)
        ->column('total_memory_disp')->type('string')->nulls(false)
        ->column('total_memory')->type('double')->nulls(false)
        ->column('available_memory_disp')->type('string')->nulls(false)
        ->column('available_memory')->type('double')->nulls(false)
        ->column('used_memory_disp')->type('string')->nulls(false)
        ->column('used_memory')->type('double')->nulls(false)
        ->column('server_id')->type('integer')->nulls(false)
        ->primaryKey('server_memory_id')->name('server_memory_id_pk')->autoIncrement()

->end();
